version: "3.1"
services:

    mysql:
        image: mysql:5.6
        container_name: mpth-mysql
        working_dir: /application
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root_pw
            - MYSQL_DATABASE=database_name
            - MYSQL_USER=mysql_user
            - MYSQL_PASSWORD=mysql_password

    webserver:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: mpth-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./ansible/roles/common/files/:/etc/nginc/certs
        ports:
            - "8080:443"
            - "8081:80"
        links:
            - php-fpm

    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        container_name: mpth-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        links:
            - mysql
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=database_name
            - DB_USERNAME=mysql_user
            - DB_PASSWORD=mysql_password

    artisan:
        build:
            context: .
            dockerfile: docker/artisan/Dockerfile
        container_name: mpth-artisan
        working_dir: /application/api
        volumes:
            - .:/application
        links:
            - mysql
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=database_name
            - DB_USERNAME=mysql_user
            - DB_PASSWORD=mysql_password

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mypth-mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
